"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object_schema import CustomObjectSchema
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['CustomObjectSchema'] = CustomObjectSchema
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_custom_object_schemas_response import GetCustomObjectSchemasResponse


class TestGetCustomObjectSchemasResponse(unittest.TestCase):
    """GetCustomObjectSchemasResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCustomObjectSchemasResponse(self):
        """Test GetCustomObjectSchemasResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCustomObjectSchemasResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
