"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.8
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.cost_of_goods_sold import CostOfGoodsSold
from apideck.model.currency import Currency
from apideck.model.custom_mappings import CustomMappings
from apideck.model.expenses import Expenses
from apideck.model.income import Income
from apideck.model.other_expenses import OtherExpenses
from apideck.model.other_income import OtherIncome
from apideck.model.profit_and_loss_indicator import ProfitAndLossIndicator
from apideck.model.uncategorized_accounts import UncategorizedAccounts
globals()['CostOfGoodsSold'] = CostOfGoodsSold
globals()['Currency'] = Currency
globals()['CustomMappings'] = CustomMappings
globals()['Expenses'] = Expenses
globals()['Income'] = Income
globals()['OtherExpenses'] = OtherExpenses
globals()['OtherIncome'] = OtherIncome
globals()['ProfitAndLossIndicator'] = ProfitAndLossIndicator
globals()['UncategorizedAccounts'] = UncategorizedAccounts
from apideck.model.profit_and_loss import ProfitAndLoss


class TestProfitAndLoss(unittest.TestCase):
    """ProfitAndLoss unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfitAndLoss(self):
        """Test ProfitAndLoss"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProfitAndLoss()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
