"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.currency import Currency
globals()['Currency'] = Currency
from apideck.model.ecommerce_order_refund import EcommerceOrderRefund


class TestEcommerceOrderRefund(unittest.TestCase):
    """EcommerceOrderRefund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcommerceOrderRefund(self):
        """Test EcommerceOrderRefund"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EcommerceOrderRefund()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
