"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.sort_direction import SortDirection
globals()['SortDirection'] = SortDirection
from apideck.model.custom_objects_sort import CustomObjectsSort


class TestCustomObjectsSort(unittest.TestCase):
    """CustomObjectsSort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomObjectsSort(self):
        """Test CustomObjectsSort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomObjectsSort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
