"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.15.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.contact import Contact
from apideck.model.raw import Raw
globals()['Contact'] = Contact
globals()['Raw'] = Raw
from apideck.model.get_contact_response import GetContactResponse


class TestGetContactResponse(unittest.TestCase):
    """GetContactResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetContactResponse(self):
        """Test GetContactResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetContactResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
