"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.8
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.collection_ticket_comment import CollectionTicketComment
from apideck.model.raw import Raw
globals()['CollectionTicketComment'] = CollectionTicketComment
globals()['Raw'] = Raw
from apideck.model.get_comment_response import GetCommentResponse


class TestGetCommentResponse(unittest.TestCase):
    """GetCommentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCommentResponse(self):
        """Test GetCommentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCommentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
