"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.7
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.bank_feed_statement import BankFeedStatement
from apideck.model.raw import Raw
globals()['BankFeedStatement'] = BankFeedStatement
globals()['Raw'] = Raw
from apideck.model.get_bank_feed_statement_response import GetBankFeedStatementResponse


class TestGetBankFeedStatementResponse(unittest.TestCase):
    """GetBankFeedStatementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBankFeedStatementResponse(self):
        """Test GetBankFeedStatementResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBankFeedStatementResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
