"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object_schema_options import CustomObjectSchemaOptions
globals()['CustomObjectSchemaOptions'] = CustomObjectSchemaOptions
from apideck.model.custom_object_schema_fields import CustomObjectSchemaFields


class TestCustomObjectSchemaFields(unittest.TestCase):
    """CustomObjectSchemaFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomObjectSchemaFields(self):
        """Test CustomObjectSchemaFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomObjectSchemaFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
