"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_sheet_assets_account import BalanceSheetAssetsAccount
from apideck.model.balance_sheet_equity_account import BalanceSheetEquityAccount
from apideck.model.balance_sheet_liabilities_account import BalanceSheetLiabilitiesAccount
from apideck.model.balance_sheet_uncategorized_items_account import BalanceSheetUncategorizedItemsAccount
from apideck.model.currency import Currency
from apideck.model.custom_mappings import CustomMappings
globals()['BalanceSheetAssetsAccount'] = BalanceSheetAssetsAccount
globals()['BalanceSheetEquityAccount'] = BalanceSheetEquityAccount
globals()['BalanceSheetLiabilitiesAccount'] = BalanceSheetLiabilitiesAccount
globals()['BalanceSheetUncategorizedItemsAccount'] = BalanceSheetUncategorizedItemsAccount
globals()['Currency'] = Currency
globals()['CustomMappings'] = CustomMappings
from apideck.model.balance_sheet_reports import BalanceSheetReports


class TestBalanceSheetReports(unittest.TestCase):
    """BalanceSheetReports unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceSheetReports(self):
        """Test BalanceSheetReports"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalanceSheetReports()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
