"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.15.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.purchase_order import PurchaseOrder
from apideck.model.raw import Raw
globals()['PurchaseOrder'] = PurchaseOrder
globals()['Raw'] = Raw
from apideck.model.get_purchase_order_response import GetPurchaseOrderResponse


class TestGetPurchaseOrderResponse(unittest.TestCase):
    """GetPurchaseOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPurchaseOrderResponse(self):
        """Test GetPurchaseOrderResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPurchaseOrderResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
