"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.8
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.lead import Lead
from apideck.model.raw import Raw
globals()['Lead'] = Lead
globals()['Raw'] = Raw
from apideck.model.get_lead_response import GetLeadResponse


class TestGetLeadResponse(unittest.TestCase):
    """GetLeadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetLeadResponse(self):
        """Test GetLeadResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetLeadResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
