"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.14.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_mapping import CustomMapping
from apideck.model.raw import Raw
globals()['CustomMapping'] = CustomMapping
globals()['Raw'] = Raw
from apideck.model.get_custom_mappings_response import GetCustomMappingsResponse


class TestGetCustomMappingsResponse(unittest.TestCase):
    """GetCustomMappingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCustomMappingsResponse(self):
        """Test GetCustomMappingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCustomMappingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
