"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.raw import Raw
from apideck.model.supplier import Supplier
globals()['Raw'] = Raw
globals()['Supplier'] = Supplier
from apideck.model.get_supplier_response import GetSupplierResponse


class TestGetSupplierResponse(unittest.TestCase):
    """GetSupplierResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSupplierResponse(self):
        """Test GetSupplierResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSupplierResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
