"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.ecommerce_customer import EcommerceCustomer
from apideck.model.raw import Raw
globals()['EcommerceCustomer'] = EcommerceCustomer
globals()['Raw'] = Raw
from apideck.model.get_ecommerce_customer_response import GetEcommerceCustomerResponse


class TestGetEcommerceCustomerResponse(unittest.TestCase):
    """GetEcommerceCustomerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEcommerceCustomerResponse(self):
        """Test GetEcommerceCustomerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEcommerceCustomerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
