"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.11.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.ecommerce_event_type import EcommerceEventType


class TestEcommerceEventType(unittest.TestCase):
    """EcommerceEventType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcommerceEventType(self):
        """Test EcommerceEventType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EcommerceEventType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
