"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.pipeline import Pipeline
from apideck.model.raw import Raw
globals()['Pipeline'] = Pipeline
globals()['Raw'] = Raw
from apideck.model.get_pipeline_response import GetPipelineResponse


class TestGetPipelineResponse(unittest.TestCase):
    """GetPipelineResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPipelineResponse(self):
        """Test GetPipelineResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPipelineResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
