"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.api import Api
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['Api'] = Api
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_apis_response import GetApisResponse


class TestGetApisResponse(unittest.TestCase):
    """GetApisResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetApisResponse(self):
        """Test GetApisResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetApisResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
