"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.11.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_by_transaction import BalanceByTransaction


class TestBalanceByTransaction(unittest.TestCase):
    """BalanceByTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceByTransaction(self):
        """Test BalanceByTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalanceByTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
