"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.raw import Raw
from apideck.model.unified_id import UnifiedId
globals()['Raw'] = Raw
globals()['UnifiedId'] = UnifiedId
from apideck.model.delete_bank_feed_statement_response import DeleteBankFeedStatementResponse


class TestDeleteBankFeedStatementResponse(unittest.TestCase):
    """DeleteBankFeedStatementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteBankFeedStatementResponse(self):
        """Test DeleteBankFeedStatementResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteBankFeedStatementResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
