"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.9
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.raw import Raw
from apideck.model.unified_id import UnifiedId
globals()['Raw'] = Raw
globals()['UnifiedId'] = UnifiedId
from apideck.model.create_bank_feed_account_response import CreateBankFeedAccountResponse


class TestCreateBankFeedAccountResponse(unittest.TestCase):
    """CreateBankFeedAccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateBankFeedAccountResponse(self):
        """Test CreateBankFeedAccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateBankFeedAccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
