"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.sort_direction import SortDirection
globals()['SortDirection'] = SortDirection
from apideck.model.custom_object_schemas_sort import CustomObjectSchemasSort


class TestCustomObjectSchemasSort(unittest.TestCase):
    """CustomObjectSchemasSort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomObjectSchemasSort(self):
        """Test CustomObjectSchemasSort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomObjectSchemasSort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
