"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.5
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.expense import Expense
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['Expense'] = Expense
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_expenses_response import GetExpensesResponse


class TestGetExpensesResponse(unittest.TestCase):
    """GetExpensesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetExpensesResponse(self):
        """Test GetExpensesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetExpensesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
