"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.raw import Raw
from apideck.model.unified_id import UnifiedId
globals()['Raw'] = Raw
globals()['UnifiedId'] = UnifiedId
from apideck.model.delete_custom_object_response import DeleteCustomObjectResponse


class TestDeleteCustomObjectResponse(unittest.TestCase):
    """DeleteCustomObjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteCustomObjectResponse(self):
        """Test DeleteCustomObjectResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteCustomObjectResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
