"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 9.7.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.from_apideck_model_currency_import_currency import FromApideckModelCurrencyImportCurrency
from apideck.model.from_apideck_model_payment_unit_import_payment_unit import FromApideckModelPaymentUnitImportPaymentUnit
from apideck.model.globals_currency_currency import GlobalsCurrencyCurrency
from apideck.model.globals_payment_unit_payment_unit import GlobalsPaymentUnitPaymentUnit
globals()['from apideck.model.currency import Currency'] = from apideck.model.currency import Currency
globals()['from apideck.model.payment_unit import PaymentUnit'] = from apideck.model.payment_unit import PaymentUnit
globals()['globals()['Currency'] = Currency'] = globals()['Currency'] = Currency
globals()['globals()['PaymentUnit'] = PaymentUnit'] = globals()['PaymentUnit'] = PaymentUnit
from apideck.model.compensation import Compensation


class TestCompensation(unittest.TestCase):
    """Compensation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompensation(self):
        """Test Compensation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Compensation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
