"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.7
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.attachment import Attachment
from apideck.model.raw import Raw
globals()['Attachment'] = Attachment
globals()['Raw'] = Raw
from apideck.model.get_attachment_response import GetAttachmentResponse


class TestGetAttachmentResponse(unittest.TestCase):
    """GetAttachmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAttachmentResponse(self):
        """Test GetAttachmentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAttachmentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
