"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.credit_or_debit import CreditOrDebit


class TestCreditOrDebit(unittest.TestCase):
    """CreditOrDebit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreditOrDebit(self):
        """Test CreditOrDebit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreditOrDebit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
