"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.7
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.raw import Raw
from apideck.model.unified_id import UnifiedId
globals()['Raw'] = Raw
globals()['UnifiedId'] = UnifiedId
from apideck.model.create_bank_feed_statement_response import CreateBankFeedStatementResponse


class TestCreateBankFeedStatementResponse(unittest.TestCase):
    """CreateBankFeedStatementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateBankFeedStatementResponse(self):
        """Test CreateBankFeedStatementResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateBankFeedStatementResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
