"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.collection_ticket_comment import CollectionTicketComment
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['CollectionTicketComment'] = CollectionTicketComment
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_comments_response import GetCommentsResponse


class TestGetCommentsResponse(unittest.TestCase):
    """GetCommentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCommentsResponse(self):
        """Test GetCommentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCommentsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
