"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_sheet import BalanceSheet
from apideck.model.raw import Raw
globals()['BalanceSheet'] = BalanceSheet
globals()['Raw'] = Raw
from apideck.model.get_balance_sheet_response import GetBalanceSheetResponse


class TestGetBalanceSheetResponse(unittest.TestCase):
    """GetBalanceSheetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBalanceSheetResponse(self):
        """Test GetBalanceSheetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBalanceSheetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
