"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.9
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.drive_group import DriveGroup
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['DriveGroup'] = DriveGroup
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_drive_groups_response import GetDriveGroupsResponse


class TestGetDriveGroupsResponse(unittest.TestCase):
    """GetDriveGroupsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDriveGroupsResponse(self):
        """Test GetDriveGroupsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDriveGroupsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
