"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.14.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_mapping import CustomMapping
from apideck.model.raw import Raw
globals()['CustomMapping'] = CustomMapping
globals()['Raw'] = Raw
from apideck.model.create_custom_mapping_response import CreateCustomMappingResponse


class TestCreateCustomMappingResponse(unittest.TestCase):
    """CreateCustomMappingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCustomMappingResponse(self):
        """Test CreateCustomMappingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCustomMappingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
