"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.15.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.profit_and_loss_records import ProfitAndLossRecords
from apideck.model.profit_and_loss_type import ProfitAndLossType
globals()['ProfitAndLossRecords'] = ProfitAndLossRecords
globals()['ProfitAndLossType'] = ProfitAndLossType
from apideck.model.expenses import Expenses


class TestExpenses(unittest.TestCase):
    """Expenses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpenses(self):
        """Test Expenses"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Expenses()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
