"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 9.7.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.from_apideck_model_address_import_address import FromApideckModelAddressImportAddress
from apideck.model.from_apideck_model_currency_import_currency import FromApideckModelCurrencyImportCurrency
from apideck.model.from_apideck_model_payment_unit_import_payment_unit import FromApideckModelPaymentUnitImportPaymentUnit
from apideck.model.globals_address_address import GlobalsAddressAddress
from apideck.model.globals_currency_currency import GlobalsCurrencyCurrency
from apideck.model.globals_payment_unit_payment_unit import GlobalsPaymentUnitPaymentUnit
globals()['from apideck.model.address import Address'] = from apideck.model.address import Address
globals()['from apideck.model.currency import Currency'] = from apideck.model.currency import Currency
globals()['from apideck.model.payment_unit import PaymentUnit'] = from apideck.model.payment_unit import PaymentUnit
globals()['globals()['Address'] = Address'] = globals()['Address'] = Address
globals()['globals()['Currency'] = Currency'] = globals()['Currency'] = Currency
globals()['globals()['PaymentUnit'] = PaymentUnit'] = globals()['PaymentUnit'] = PaymentUnit
from apideck.model.job import Job


class TestJob(unittest.TestCase):
    """Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJob(self):
        """Test Job"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Job()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
