"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.4
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.create_callback_state_response_data import CreateCallbackStateResponseData
from apideck.model.raw import Raw
globals()['CreateCallbackStateResponseData'] = CreateCallbackStateResponseData
globals()['Raw'] = Raw
from apideck.model.create_callback_state_response import CreateCallbackStateResponse


class TestCreateCallbackStateResponse(unittest.TestCase):
    """CreateCallbackStateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCallbackStateResponse(self):
        """Test CreateCallbackStateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCallbackStateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
