"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.profit_and_loss_records import ProfitAndLossRecords
from apideck.model.profit_and_loss_type import ProfitAndLossType
globals()['ProfitAndLossRecords'] = ProfitAndLossRecords
globals()['ProfitAndLossType'] = ProfitAndLossType
from apideck.model.cost_of_goods_sold import CostOfGoodsSold


class TestCostOfGoodsSold(unittest.TestCase):
    """CostOfGoodsSold unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCostOfGoodsSold(self):
        """Test CostOfGoodsSold"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CostOfGoodsSold()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
