"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.invoice import Invoice
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['Invoice'] = Invoice
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_invoices_response import GetInvoicesResponse


class TestGetInvoicesResponse(unittest.TestCase):
    """GetInvoicesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInvoicesResponse(self):
        """Test GetInvoicesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetInvoicesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
