"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.15.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.outstanding_balance_by_supplier import OutstandingBalanceBySupplier
globals()['OutstandingBalanceBySupplier'] = OutstandingBalanceBySupplier
from apideck.model.aged_creditors import AgedCreditors


class TestAgedCreditors(unittest.TestCase):
    """AgedCreditors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgedCreditors(self):
        """Test AgedCreditors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AgedCreditors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
