"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.6
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.bill import Bill
from apideck.model.raw import Raw
globals()['Bill'] = Bill
globals()['Raw'] = Raw
from apideck.model.get_bill_response import GetBillResponse


class TestGetBillResponse(unittest.TestCase):
    """GetBillResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBillResponse(self):
        """Test GetBillResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBillResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
