"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.11.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.outstanding_balance_by_customer import OutstandingBalanceByCustomer
globals()['OutstandingBalanceByCustomer'] = OutstandingBalanceByCustomer
from apideck.model.aged_debtors import AgedDebtors


class TestAgedDebtors(unittest.TestCase):
    """AgedDebtors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgedDebtors(self):
        """Test AgedDebtors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AgedDebtors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
