"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.9
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.bank_feed_account import BankFeedAccount
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['BankFeedAccount'] = BankFeedAccount
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_bank_feed_accounts_response import GetBankFeedAccountsResponse


class TestGetBankFeedAccountsResponse(unittest.TestCase):
    """GetBankFeedAccountsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBankFeedAccountsResponse(self):
        """Test GetBankFeedAccountsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBankFeedAccountsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
