"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.6
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.bank_feed_statement import BankFeedStatement
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['BankFeedStatement'] = BankFeedStatement
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_bank_feed_statements_response import GetBankFeedStatementsResponse


class TestGetBankFeedStatementsResponse(unittest.TestCase):
    """GetBankFeedStatementsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBankFeedStatementsResponse(self):
        """Test GetBankFeedStatementsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBankFeedStatementsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
