"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.14.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.application import Application
from apideck.model.raw import Raw
globals()['Application'] = Application
globals()['Raw'] = Raw
from apideck.model.get_application_response import GetApplicationResponse


class TestGetApplicationResponse(unittest.TestCase):
    """GetApplicationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetApplicationResponse(self):
        """Test GetApplicationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetApplicationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
