"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.14.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.order import Order
from apideck.model.raw import Raw
globals()['Order'] = Order
globals()['Raw'] = Raw
from apideck.model.get_order_response import GetOrderResponse


class TestGetOrderResponse(unittest.TestCase):
    """GetOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOrderResponse(self):
        """Test GetOrderResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetOrderResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
