"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.11.4
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.outstanding_balance_by_currency import OutstandingBalanceByCurrency
globals()['OutstandingBalanceByCurrency'] = OutstandingBalanceByCurrency
from apideck.model.outstanding_balance_by_supplier import OutstandingBalanceBySupplier


class TestOutstandingBalanceBySupplier(unittest.TestCase):
    """OutstandingBalanceBySupplier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutstandingBalanceBySupplier(self):
        """Test OutstandingBalanceBySupplier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OutstandingBalanceBySupplier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
