"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 9.7.6
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.currency import Currency
globals()['Currency'] = Currency
from apideck.model.employee_bank_accounts import EmployeeBankAccounts


class TestEmployeeBankAccounts(unittest.TestCase):
    """EmployeeBankAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmployeeBankAccounts(self):
        """Test EmployeeBankAccounts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmployeeBankAccounts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
