"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.invoice_item import InvoiceItem
from apideck.model.raw import Raw
globals()['InvoiceItem'] = InvoiceItem
globals()['Raw'] = Raw
from apideck.model.get_invoice_item_response import GetInvoiceItemResponse


class TestGetInvoiceItemResponse(unittest.TestCase):
    """GetInvoiceItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInvoiceItemResponse(self):
        """Test GetInvoiceItemResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetInvoiceItemResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
