"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.8
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.employee import Employee
from apideck.model.raw import Raw
globals()['Employee'] = Employee
globals()['Raw'] = Raw
from apideck.model.get_employee_response import GetEmployeeResponse


class TestGetEmployeeResponse(unittest.TestCase):
    """GetEmployeeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEmployeeResponse(self):
        """Test GetEmployeeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEmployeeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
