"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.9
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.bank_feed_statement_transactions import BankFeedStatementTransactions
from apideck.model.credit_or_debit import CreditOrDebit
globals()['BankFeedStatementTransactions'] = BankFeedStatementTransactions
globals()['CreditOrDebit'] = CreditOrDebit
from apideck.model.bank_feed_statement import BankFeedStatement


class TestBankFeedStatement(unittest.TestCase):
    """BankFeedStatement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankFeedStatement(self):
        """Test BankFeedStatement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankFeedStatement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
