"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.4
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.invoice_payment_allocations import InvoicePaymentAllocations


class TestInvoicePaymentAllocations(unittest.TestCase):
    """InvoicePaymentAllocations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoicePaymentAllocations(self):
        """Test InvoicePaymentAllocations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvoicePaymentAllocations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
