"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object_schema_fields import CustomObjectSchemaFields
from apideck.model.pass_through_body import PassThroughBody
globals()['CustomObjectSchemaFields'] = CustomObjectSchemaFields
globals()['PassThroughBody'] = PassThroughBody
from apideck.model.custom_object_schema import CustomObjectSchema


class TestCustomObjectSchema(unittest.TestCase):
    """CustomObjectSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomObjectSchema(self):
        """Test CustomObjectSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomObjectSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
