"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.aged_creditors import AgedCreditors
from apideck.model.raw import Raw
globals()['AgedCreditors'] = AgedCreditors
globals()['Raw'] = Raw
from apideck.model.get_aged_creditors_response import GetAgedCreditorsResponse


class TestGetAgedCreditorsResponse(unittest.TestCase):
    """GetAgedCreditorsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAgedCreditorsResponse(self):
        """Test GetAgedCreditorsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAgedCreditorsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
