"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.expense import Expense
from apideck.model.raw import Raw
globals()['Expense'] = Expense
globals()['Raw'] = Raw
from apideck.model.get_expense_response import GetExpenseResponse


class TestGetExpenseResponse(unittest.TestCase):
    """GetExpenseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetExpenseResponse(self):
        """Test GetExpenseResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetExpenseResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
