"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.15.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.profit_and_loss_records import ProfitAndLossRecords
from apideck.model.profit_and_loss_type import ProfitAndLossType
globals()['ProfitAndLossRecords'] = ProfitAndLossRecords
globals()['ProfitAndLossType'] = ProfitAndLossType
from apideck.model.uncategorized_accounts import UncategorizedAccounts


class TestUncategorizedAccounts(unittest.TestCase):
    """UncategorizedAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUncategorizedAccounts(self):
        """Test UncategorizedAccounts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UncategorizedAccounts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
