"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.4
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.ecommerce_customer import EcommerceCustomer
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['EcommerceCustomer'] = EcommerceCustomer
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_ecommerce_customers_response import GetEcommerceCustomersResponse


class TestGetEcommerceCustomersResponse(unittest.TestCase):
    """GetEcommerceCustomersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEcommerceCustomersResponse(self):
        """Test GetEcommerceCustomersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEcommerceCustomersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
