"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.15.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.get_consumers_response_data import GetConsumersResponseData
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['GetConsumersResponseData'] = GetConsumersResponseData
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_consumers_response import GetConsumersResponse


class TestGetConsumersResponse(unittest.TestCase):
    """GetConsumersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetConsumersResponse(self):
        """Test GetConsumersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetConsumersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
