"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.8
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_mappings import CustomMappings


class TestCustomMappings(unittest.TestCase):
    """CustomMappings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomMappings(self):
        """Test CustomMappings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomMappings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
