"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.credit_or_debit import CreditOrDebit
globals()['CreditOrDebit'] = CreditOrDebit
from apideck.model.bank_feed_statement_transactions import BankFeedStatementTransactions


class TestBankFeedStatementTransactions(unittest.TestCase):
    """BankFeedStatementTransactions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankFeedStatementTransactions(self):
        """Test BankFeedStatementTransactions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankFeedStatementTransactions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
