"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.7
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.message import Message
from apideck.model.raw import Raw
globals()['Message'] = Message
globals()['Raw'] = Raw
from apideck.model.get_message_response import GetMessageResponse


class TestGetMessageResponse(unittest.TestCase):
    """GetMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetMessageResponse(self):
        """Test GetMessageResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetMessageResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
