"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.15.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.outstanding_balance_by_currency import OutstandingBalanceByCurrency
globals()['OutstandingBalanceByCurrency'] = OutstandingBalanceByCurrency
from apideck.model.outstanding_balance_by_customer import OutstandingBalanceByCustomer


class TestOutstandingBalanceByCustomer(unittest.TestCase):
    """OutstandingBalanceByCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutstandingBalanceByCustomer(self):
        """Test OutstandingBalanceByCustomer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OutstandingBalanceByCustomer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
