"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.connection import Connection
from apideck.model.raw import Raw
globals()['Connection'] = Connection
globals()['Raw'] = Raw
from apideck.model.get_connection_response import GetConnectionResponse


class TestGetConnectionResponse(unittest.TestCase):
    """GetConnectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetConnectionResponse(self):
        """Test GetConnectionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetConnectionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
