"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object_fields import CustomObjectFields
from apideck.model.pass_through_body import PassThroughBody
globals()['CustomObjectFields'] = CustomObjectFields
globals()['PassThroughBody'] = PassThroughBody
from apideck.model.custom_object import CustomObject


class TestCustomObject(unittest.TestCase):
    """CustomObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomObject(self):
        """Test CustomObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
