"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.9
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.bank_feed_account import BankFeedAccount
from apideck.model.raw import Raw
globals()['BankFeedAccount'] = BankFeedAccount
globals()['Raw'] = Raw
from apideck.model.get_bank_feed_account_response import GetBankFeedAccountResponse


class TestGetBankFeedAccountResponse(unittest.TestCase):
    """GetBankFeedAccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBankFeedAccountResponse(self):
        """Test GetBankFeedAccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBankFeedAccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
