"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.6
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.opportunity import Opportunity
from apideck.model.raw import Raw
globals()['Opportunity'] = Opportunity
globals()['Raw'] = Raw
from apideck.model.get_opportunity_response import GetOpportunityResponse


class TestGetOpportunityResponse(unittest.TestCase):
    """GetOpportunityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetOpportunityResponse(self):
        """Test GetOpportunityResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetOpportunityResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
