"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.8
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.ecommerce_order import EcommerceOrder
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['EcommerceOrder'] = EcommerceOrder
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_ecommerce_orders_response import GetEcommerceOrdersResponse


class TestGetEcommerceOrdersResponse(unittest.TestCase):
    """GetEcommerceOrdersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEcommerceOrdersResponse(self):
        """Test GetEcommerceOrdersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEcommerceOrdersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
