"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.11.5
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.modifier_group import ModifierGroup
from apideck.model.raw import Raw
globals()['ModifierGroup'] = ModifierGroup
globals()['Raw'] = Raw
from apideck.model.get_modifier_group_response import GetModifierGroupResponse


class TestGetModifierGroupResponse(unittest.TestCase):
    """GetModifierGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetModifierGroupResponse(self):
        """Test GetModifierGroupResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetModifierGroupResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
