"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.14.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.collection import Collection
from apideck.model.raw import Raw
globals()['Collection'] = Collection
globals()['Raw'] = Raw
from apideck.model.get_collection_response import GetCollectionResponse


class TestGetCollectionResponse(unittest.TestCase):
    """GetCollectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCollectionResponse(self):
        """Test GetCollectionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCollectionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
