"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object_schema import CustomObjectSchema
from apideck.model.raw import Raw
globals()['CustomObjectSchema'] = CustomObjectSchema
globals()['Raw'] = Raw
from apideck.model.create_custom_object_schema_response import CreateCustomObjectSchemaResponse


class TestCreateCustomObjectSchemaResponse(unittest.TestCase):
    """CreateCustomObjectSchemaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateCustomObjectSchemaResponse(self):
        """Test CreateCustomObjectSchemaResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateCustomObjectSchemaResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
