"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.8
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.profit_and_loss_indicator import ProfitAndLossIndicator


class TestProfitAndLossIndicator(unittest.TestCase):
    """ProfitAndLossIndicator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfitAndLossIndicator(self):
        """Test ProfitAndLossIndicator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProfitAndLossIndicator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
