"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object_schema_options import CustomObjectSchemaOptions


class TestCustomObjectSchemaOptions(unittest.TestCase):
    """CustomObjectSchemaOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomObjectSchemaOptions(self):
        """Test CustomObjectSchemaOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomObjectSchemaOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
