"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.applicant import Applicant
from apideck.model.raw import Raw
globals()['Applicant'] = Applicant
globals()['Raw'] = Raw
from apideck.model.get_applicant_response import GetApplicantResponse


class TestGetApplicantResponse(unittest.TestCase):
    """GetApplicantResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetApplicantResponse(self):
        """Test GetApplicantResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetApplicantResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
