"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.pipeline import Pipeline
from apideck.model.raw import Raw
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Pipeline'] = Pipeline
globals()['Raw'] = Raw
from apideck.model.get_pipelines_response import GetPipelinesResponse


class TestGetPipelinesResponse(unittest.TestCase):
    """GetPipelinesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPipelinesResponse(self):
        """Test GetPipelinesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPipelinesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
