"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object import CustomObject
from apideck.model.raw import Raw
globals()['CustomObject'] = CustomObject
globals()['Raw'] = Raw
from apideck.model.get_custom_object_response import GetCustomObjectResponse


class TestGetCustomObjectResponse(unittest.TestCase):
    """GetCustomObjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCustomObjectResponse(self):
        """Test GetCustomObjectResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCustomObjectResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
