"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.payment import Payment
from apideck.model.raw import Raw
globals()['Payment'] = Payment
globals()['Raw'] = Raw
from apideck.model.get_payment_response import GetPaymentResponse


class TestGetPaymentResponse(unittest.TestCase):
    """GetPaymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPaymentResponse(self):
        """Test GetPaymentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPaymentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
