"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.11.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.sort_direction import SortDirection
globals()['SortDirection'] = SortDirection
from apideck.model.invoice_items_sort import InvoiceItemsSort


class TestInvoiceItemsSort(unittest.TestCase):
    """InvoiceItemsSort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvoiceItemsSort(self):
        """Test InvoiceItemsSort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvoiceItemsSort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
