"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.17.2
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.custom_object import CustomObject
from apideck.model.links import Links
from apideck.model.meta import Meta
from apideck.model.raw import Raw
globals()['CustomObject'] = CustomObject
globals()['Links'] = Links
globals()['Meta'] = Meta
globals()['Raw'] = Raw
from apideck.model.get_custom_objects_response import GetCustomObjectsResponse


class TestGetCustomObjectsResponse(unittest.TestCase):
    """GetCustomObjectsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCustomObjectsResponse(self):
        """Test GetCustomObjectsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCustomObjectsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
