"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.9.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.outstanding_balance_by_currency import OutstandingBalanceByCurrency
globals()['OutstandingBalanceByCurrency'] = OutstandingBalanceByCurrency
from apideck.model.outstanding_balance import OutstandingBalance


class TestOutstandingBalance(unittest.TestCase):
    """OutstandingBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutstandingBalance(self):
        """Test OutstandingBalance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OutstandingBalance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
