"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.9.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_by_transaction import BalanceByTransaction
globals()['BalanceByTransaction'] = BalanceByTransaction
from apideck.model.balance_by_period import BalanceByPeriod


class TestBalanceByPeriod(unittest.TestCase):
    """BalanceByPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceByPeriod(self):
        """Test BalanceByPeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalanceByPeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
