"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.11.5
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.invoice_response import InvoiceResponse
from apideck.model.raw import Raw
globals()['InvoiceResponse'] = InvoiceResponse
globals()['Raw'] = Raw
from apideck.model.create_invoice_response import CreateInvoiceResponse


class TestCreateInvoiceResponse(unittest.TestCase):
    """CreateInvoiceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateInvoiceResponse(self):
        """Test CreateInvoiceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateInvoiceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
