"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_by_period import BalanceByPeriod
from apideck.model.currency import Currency
globals()['BalanceByPeriod'] = BalanceByPeriod
globals()['Currency'] = Currency
from apideck.model.outstanding_balance_by_currency import OutstandingBalanceByCurrency


class TestOutstandingBalanceByCurrency(unittest.TestCase):
    """OutstandingBalanceByCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutstandingBalanceByCurrency(self):
        """Test OutstandingBalanceByCurrency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OutstandingBalanceByCurrency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
