"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.16.9
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.address import Address
from apideck.model.custom_mappings import CustomMappings
from apideck.model.email import Email
from apideck.model.pass_through_body import PassThroughBody
from apideck.model.phone_number import PhoneNumber
globals()['Address'] = Address
globals()['CustomMappings'] = CustomMappings
globals()['Email'] = Email
globals()['PassThroughBody'] = PassThroughBody
globals()['PhoneNumber'] = PhoneNumber
from apideck.model.user import User


class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUser(self):
        """Test User"""
        # FIXME: construct object with mandatory attributes with example values
        # model = User()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
