"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.12.1
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.payroll import Payroll
from apideck.model.raw import Raw
globals()['Payroll'] = Payroll
globals()['Raw'] = Raw
from apideck.model.get_payrolls_response import GetPayrollsResponse


class TestGetPayrollsResponse(unittest.TestCase):
    """GetPayrollsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPayrollsResponse(self):
        """Test GetPayrollsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPayrollsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
