"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.13.0
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.job import Job
from apideck.model.raw import Raw
globals()['Job'] = Job
globals()['Raw'] = Raw
from apideck.model.get_job_response import GetJobResponse


class TestGetJobResponse(unittest.TestCase):
    """GetJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetJobResponse(self):
        """Test GetJobResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetJobResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
