name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
      
jobs:
  release:
    if: "github.event.pull_request.merged == true"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: 0.0.2
      - name: Delete Branch
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            github.rest.git.deleteRef({
              owner: '$',
              repo: '$',
              ref: 'heads/$'
            })
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: $
        with:
          branch: 'generator-update'
          sha: '$'

